// 球队阵容数据 - 基于2026年世界杯预选赛和最新国家队名单
export interface Player {
  name: string;
  number: number;
  position: "GK" | "DF" | "MF" | "FW";
  club: string;
  age: number;
  isCaptain?: boolean;
}

export interface TeamSquad {
  coach: string;
  coachNationality: string;
  formation: string;
  players: Player[];
}

// 示例球队阵容数据（主要参赛队伍）
export const teamSquads: Record<string, TeamSquad> = {
  Argentina: {
    coach: "Lionel Scaloni",
    coachNationality: "Argentina",
    formation: "4-3-3",
    players: [
      { name: "Emiliano Martínez", number: 23, position: "GK", club: "Aston Villa", age: 33 },
      { name: "Gerónimo Rulli", number: 12, position: "GK", club: "Marseille", age: 34 },
      { name: "Nahuel Molina", number: 26, position: "DF", club: "Atlético Madrid", age: 28 },
      { name: "Cristian Romero", number: 13, position: "DF", club: "Tottenham", age: 28 },
      { name: "Nicolás Otamendi", number: 19, position: "DF", club: "Benfica", age: 38 },
      { name: "Lisandro Martínez", number: 25, position: "DF", club: "Manchester United", age: 28 },
      { name: "Nicolás Tagliafico", number: 3, position: "DF", club: "Lyon", age: 33 },
      { name: "Rodrigo De Paul", number: 7, position: "MF", club: "Atlético Madrid", age: 32 },
      { name: "Leandro Paredes", number: 5, position: "MF", club: "Roma", age: 32 },
      { name: "Enzo Fernández", number: 24, position: "MF", club: "Chelsea", age: 25 },
      { name: "Alexis Mac Allister", number: 20, position: "MF", club: "Liverpool", age: 27 },
      { name: "Giovani Lo Celso", number: 18, position: "MF", club: "Tottenham", age: 30 },
      { name: "Lionel Messi", number: 10, position: "FW", club: "Inter Miami", age: 38, isCaptain: true },
      { name: "Julián Álvarez", number: 9, position: "FW", club: "Atlético Madrid", age: 26 },
      { name: "Lautaro Martínez", number: 22, position: "FW", club: "Inter Milan", age: 28 },
      { name: "Ángel Di María", number: 11, position: "FW", club: "Benfica", age: 38 },
    ],
  },
  Brazil: {
    coach: "Dorival Júnior",
    coachNationality: "Brazil",
    formation: "4-2-3-1",
    players: [
      { name: "Alisson", number: 1, position: "GK", club: "Liverpool", age: 33 },
      { name: "Ederson", number: 23, position: "GK", club: "Manchester City", age: 32 },
      { name: "Danilo", number: 2, position: "DF", club: "Juventus", age: 35, isCaptain: true },
      { name: "Marquinhos", number: 4, position: "DF", club: "PSG", age: 32 },
      { name: "Gabriel Magalhães", number: 3, position: "DF", club: "Arsenal", age: 28 },
      { name: "Wendell", number: 6, position: "DF", club: "Porto", age: 33 },
      { name: "Guilherme Arana", number: 16, position: "DF", club: "Atlético Mineiro", age: 29 },
      { name: "Casemiro", number: 5, position: "MF", club: "Manchester United", age: 34 },
      { name: "Bruno Guimarães", number: 8, position: "MF", club: "Newcastle", age: 28 },
      { name: "Lucas Paquetá", number: 10, position: "MF", club: "West Ham", age: 28 },
      { name: "Raphinha", number: 11, position: "FW", club: "Barcelona", age: 29 },
      { name: "Rodrygo", number: 7, position: "FW", club: "Real Madrid", age: 25 },
      { name: "Vinícius Jr.", number: 20, position: "FW", club: "Real Madrid", age: 25 },
      { name: "Endrick", number: 9, position: "FW", club: "Real Madrid", age: 19 },
      { name: "Gabriel Martinelli", number: 26, position: "FW", club: "Arsenal", age: 25 },
    ],
  },
  France: {
    coach: "Didier Deschamps",
    coachNationality: "France",
    formation: "4-3-3",
    players: [
      { name: "Mike Maignan", number: 16, position: "GK", club: "AC Milan", age: 31 },
      { name: "Alphonse Areola", number: 23, position: "GK", club: "West Ham", age: 33 },
      { name: "Jules Koundé", number: 5, position: "DF", club: "Barcelona", age: 27 },
      { name: "Dayot Upamecano", number: 4, position: "DF", club: "Bayern Munich", age: 27 },
      { name: "William Saliba", number: 17, position: "DF", club: "Arsenal", age: 25 },
      { name: "Theo Hernández", number: 22, position: "DF", club: "AC Milan", age: 28 },
      { name: "N'Golo Kanté", number: 13, position: "MF", club: "Al-Ittihad", age: 35 },
      { name: "Aurélien Tchouaméni", number: 8, position: "MF", club: "Real Madrid", age: 26 },
      { name: "Antoine Griezmann", number: 7, position: "MF", club: "Atlético Madrid", age: 35 },
      { name: "Eduardo Camavinga", number: 6, position: "MF", club: "Real Madrid", age: 23 },
      { name: "Kylian Mbappé", number: 10, position: "FW", club: "Real Madrid", age: 27, isCaptain: true },
      { name: "Ousmane Dembélé", number: 11, position: "FW", club: "PSG", age: 29 },
      { name: "Marcus Thuram", number: 15, position: "FW", club: "Inter Milan", age: 28 },
      { name: "Randal Kolo Muani", number: 12, position: "FW", club: "PSG", age: 27 },
    ],
  },
  England: {
    coach: "Thomas Tuchel",
    coachNationality: "Germany",
    formation: "4-2-3-1",
    players: [
      { name: "Jordan Pickford", number: 1, position: "GK", club: "Everton", age: 32 },
      { name: "Aaron Ramsdale", number: 23, position: "GK", club: "Southampton", age: 28 },
      { name: "Kyle Walker", number: 2, position: "DF", club: "Manchester City", age: 36 },
      { name: "John Stones", number: 5, position: "DF", club: "Manchester City", age: 32 },
      { name: "Harry Maguire", number: 6, position: "DF", club: "Manchester United", age: 33 },
      { name: "Luke Shaw", number: 3, position: "DF", club: "Manchester United", age: 31 },
      { name: "Declan Rice", number: 4, position: "MF", club: "Arsenal", age: 27 },
      { name: "Jude Bellingham", number: 10, position: "MF", club: "Real Madrid", age: 22 },
      { name: "Phil Foden", number: 11, position: "MF", club: "Manchester City", age: 26 },
      { name: "Bukayo Saka", number: 7, position: "FW", club: "Arsenal", age: 24 },
      { name: "Harry Kane", number: 9, position: "FW", club: "Bayern Munich", age: 32, isCaptain: true },
      { name: "Cole Palmer", number: 20, position: "FW", club: "Chelsea", age: 24 },
      { name: "Marcus Rashford", number: 19, position: "FW", club: "Manchester United", age: 28 },
    ],
  },
  Germany: {
    coach: "Julian Nagelsmann",
    coachNationality: "Germany",
    formation: "4-2-3-1",
    players: [
      { name: "Manuel Neuer", number: 1, position: "GK", club: "Bayern Munich", age: 40 },
      { name: "Marc-André ter Stegen", number: 22, position: "GK", club: "Barcelona", age: 34 },
      { name: "Joshua Kimmich", number: 6, position: "DF", club: "Bayern Munich", age: 31 },
      { name: "Antonio Rüdiger", number: 2, position: "DF", club: "Real Madrid", age: 33 },
      { name: "Jonathan Tah", number: 4, position: "DF", club: "Bayer Leverkusen", age: 30 },
      { name: "David Raum", number: 3, position: "DF", club: "RB Leipzig", age: 28 },
      { name: "İlkay Gündoğan", number: 21, position: "MF", club: "Barcelona", age: 35, isCaptain: true },
      { name: "Toni Kroos", number: 8, position: "MF", club: "Retired", age: 36 },
      { name: "Florian Wirtz", number: 10, position: "MF", club: "Bayer Leverkusen", age: 23 },
      { name: "Jamal Musiala", number: 14, position: "MF", club: "Bayern Munich", age: 23 },
      { name: "Leroy Sané", number: 19, position: "FW", club: "Bayern Munich", age: 30 },
      { name: "Kai Havertz", number: 7, position: "FW", club: "Arsenal", age: 27 },
      { name: "Niclas Füllkrug", number: 9, position: "FW", club: "West Ham", age: 33 },
    ],
  },
  Spain: {
    coach: "Luis de la Fuente",
    coachNationality: "Spain",
    formation: "4-3-3",
    players: [
      { name: "Unai Simón", number: 23, position: "GK", club: "Athletic Bilbao", age: 27 },
      { name: "David Raya", number: 13, position: "GK", club: "Arsenal", age: 29 },
      { name: "Dani Carvajal", number: 2, position: "DF", club: "Real Madrid", age: 34 },
      { name: "Aymeric Laporte", number: 14, position: "DF", club: "Al-Nassr", age: 32 },
      { name: "Robin Le Normand", number: 24, position: "DF", club: "Atlético Madrid", age: 28 },
      { name: "Marc Cucurella", number: 3, position: "DF", club: "Chelsea", age: 27 },
      { name: "Rodri", number: 16, position: "MF", club: "Manchester City", age: 30 },
      { name: "Pedri", number: 8, position: "MF", club: "Barcelona", age: 23 },
      { name: "Fabián Ruiz", number: 10, position: "MF", club: "PSG", age: 30 },
      { name: "Gavi", number: 6, position: "MF", club: "Barcelona", age: 21 },
      { name: "Lamine Yamal", number: 19, position: "FW", club: "Barcelona", age: 18 },
      { name: "Nico Williams", number: 11, position: "FW", club: "Athletic Bilbao", age: 24 },
      { name: "Álvaro Morata", number: 7, position: "FW", club: "AC Milan", age: 33, isCaptain: true },
      { name: "Ferran Torres", number: 21, position: "FW", club: "Barcelona", age: 26 },
    ],
  },
  Netherlands: {
    coach: "Ronald Koeman",
    coachNationality: "Netherlands",
    formation: "4-3-3",
    players: [
      { name: "Bart Verbruggen", number: 1, position: "GK", club: "Brighton", age: 23 },
      { name: "Denzel Dumfries", number: 22, position: "DF", club: "Inter Milan", age: 30 },
      { name: "Virgil van Dijk", number: 4, position: "DF", club: "Liverpool", age: 34, isCaptain: true },
      { name: "Nathan Aké", number: 5, position: "DF", club: "Manchester City", age: 31 },
      { name: "Jurriën Timber", number: 2, position: "DF", club: "Arsenal", age: 25 },
      { name: "Frenkie de Jong", number: 21, position: "MF", club: "Barcelona", age: 29 },
      { name: "Tijjani Reijnders", number: 14, position: "MF", club: "AC Milan", age: 27 },
      { name: "Xavi Simons", number: 10, position: "MF", club: "RB Leipzig", age: 23 },
      { name: "Memphis Depay", number: 10, position: "FW", club: "Corinthians", age: 32 },
      { name: "Cody Gakpo", number: 11, position: "FW", club: "Liverpool", age: 27 },
      { name: "Donyell Malen", number: 18, position: "FW", club: "Borussia Dortmund", age: 27 },
    ],
  },
  Portugal: {
    coach: "Roberto Martínez",
    coachNationality: "Spain",
    formation: "4-3-3",
    players: [
      { name: "Diogo Costa", number: 22, position: "GK", club: "Porto", age: 27 },
      { name: "Rui Patrício", number: 1, position: "GK", club: "Roma", age: 38 },
      { name: "João Cancelo", number: 20, position: "DF", club: "Al Hilal", age: 32 },
      { name: "Rúben Dias", number: 4, position: "DF", club: "Manchester City", age: 29 },
      { name: "Pepe", number: 3, position: "DF", club: "Porto", age: 43 },
      { name: "Nuno Mendes", number: 19, position: "DF", club: "PSG", age: 24 },
      { name: "Vitinha", number: 8, position: "MF", club: "PSG", age: 26 },
      { name: "Bruno Fernandes", number: 10, position: "MF", club: "Manchester United", age: 31 },
      { name: "Bernardo Silva", number: 10, position: "MF", club: "Manchester City", age: 31 },
      { name: "Cristiano Ronaldo", number: 7, position: "FW", club: "Al-Nassr", age: 41, isCaptain: true },
      { name: "Rafael Leão", number: 15, position: "FW", club: "AC Milan", age: 27 },
      { name: "Diogo Jota", number: 21, position: "FW", club: "Liverpool", age: 29 },
      { name: "Gonçalo Ramos", number: 9, position: "FW", club: "PSG", age: 25 },
    ],
  },
  USA: {
    coach: "Mauricio Pochettino",
    coachNationality: "Argentina",
    formation: "4-3-3",
    players: [
      { name: "Matt Turner", number: 1, position: "GK", club: "Crystal Palace", age: 32 },
      { name: "Ethan Horvath", number: 12, position: "GK", club: "Cardiff City", age: 31 },
      { name: "Sergiño Dest", number: 2, position: "DF", club: "PSV", age: 25 },
      { name: "Tim Ream", number: 13, position: "DF", club: "Fulham", age: 39 },
      { name: "Chris Richards", number: 4, position: "DF", club: "Crystal Palace", age: 26 },
      { name: "Antonee Robinson", number: 5, position: "DF", club: "Fulham", age: 28 },
      { name: "Tyler Adams", number: 4, position: "MF", club: "Bournemouth", age: 27 },
      { name: "Weston McKennie", number: 8, position: "MF", club: "Juventus", age: 27 },
      { name: "Yunus Musah", number: 6, position: "MF", club: "AC Milan", age: 23 },
      { name: "Giovanni Reyna", number: 7, position: "MF", club: "Borussia Dortmund", age: 23 },
      { name: "Christian Pulisic", number: 10, position: "FW", club: "AC Milan", age: 27, isCaptain: true },
      { name: "Timothy Weah", number: 21, position: "FW", club: "Juventus", age: 26 },
      { name: "Folarin Balogun", number: 20, position: "FW", club: "Monaco", age: 25 },
      { name: "Ricardo Pepi", number: 9, position: "FW", club: "PSV", age: 23 },
    ],
  },
  Mexico: {
    coach: "Javier Aguirre",
    coachNationality: "Mexico",
    formation: "4-3-3",
    players: [
      { name: "Guillermo Ochoa", number: 13, position: "GK", club: "Club América", age: 41 },
      { name: "Luis Malagón", number: 1, position: "GK", club: "Club América", age: 27 },
      { name: "Jorge Sánchez", number: 2, position: "DF", club: "Porto", age: 28 },
      { name: "César Montes", number: 3, position: "DF", club: "Almería", age: 29 },
      { name: "Johan Vásquez", number: 5, position: "DF", club: "Genoa", age: 27 },
      { name: "Jesús Gallardo", number: 23, position: "DF", club: "Monterrey", age: 32 },
      { name: "Edson Álvarez", number: 4, position: "MF", club: "West Ham", age: 28, isCaptain: true },
      { name: "Luis Chávez", number: 18, position: "MF", club: "Pachuca", age: 30 },
      { name: "Orbelín Pineda", number: 10, position: "MF", club: "AEK Athens", age: 30 },
      { name: "Hirving Lozano", number: 22, position: "FW", club: "PSV", age: 31 },
      { name: "Santiago Giménez", number: 9, position: "FW", club: "Feyenoord", age: 25 },
      { name: "Alexis Vega", number: 11, position: "FW", club: "Toluca", age: 28 },
    ],
  },
  Japan: {
    coach: "Hajime Moriyasu",
    coachNationality: "Japan",
    formation: "4-2-3-1",
    players: [
      { name: "Shuichi Gonda", number: 12, position: "GK", club: "Shimizu S-Pulse", age: 37 },
      { name: "Zion Suzuki", number: 1, position: "GK", club: "Parma", age: 22 },
      { name: "Miki Yamane", number: 4, position: "DF", club: "Celtic", age: 32 },
      { name: "Ko Itakura", number: 22, position: "DF", club: "Borussia M'gladbach", age: 29 },
      { name: "Takehiro Tomiyasu", number: 16, position: "DF", club: "Arsenal", age: 27 },
      { name: "Yuto Nagatomo", number: 5, position: "DF", club: "FC Tokyo", age: 39 },
      { name: "Wataru Endo", number: 6, position: "MF", club: "Liverpool", age: 33 },
      { name: "Hidemasa Morita", number: 8, position: "MF", club: "Sporting CP", age: 28 },
      { name: "Kaoru Mitoma", number: 7, position: "MF", club: "Brighton", age: 29 },
      { name: "Takumi Minamino", number: 10, position: "MF", club: "Monaco", age: 31 },
      { name: "Takefusa Kubo", number: 11, position: "FW", club: "Real Sociedad", age: 25 },
      { name: "Kyogo Furuhashi", number: 20, position: "FW", club: "Celtic", age: 31 },
      { name: "Ayase Ueda", number: 18, position: "FW", club: "Feyenoord", age: 26 },
    ],
  },
  "South Korea": {
    coach: "Hong Myung-bo",
    coachNationality: "South Korea",
    formation: "4-2-3-1",
    players: [
      { name: "Kim Seung-gyu", number: 1, position: "GK", club: "Al-Shabab", age: 36 },
      { name: "Jo Hyeon-woo", number: 21, position: "GK", club: "Ulsan HD", age: 35 },
      { name: "Kim Min-jae", number: 3, position: "DF", club: "Bayern Munich", age: 29 },
      { name: "Kim Young-gwon", number: 20, position: "DF", club: "Ulsan HD", age: 36 },
      { name: "Kim Jin-su", number: 6, position: "DF", club: "Jeonbuk Motors", age: 34 },
      { name: "Lee Ki-je", number: 4, position: "DF", club: "Jeonbuk Motors", age: 35 },
      { name: "Hwang In-beom", number: 8, position: "MF", club: "Feyenoord", age: 29 },
      { name: "Lee Jae-sung", number: 16, position: "MF", club: "Mainz", age: 33 },
      { name: "Lee Kang-in", number: 10, position: "MF", club: "PSG", age: 25 },
      { name: "Son Heung-min", number: 7, position: "FW", club: "Tottenham", age: 33, isCaptain: true },
      { name: "Hwang Hee-chan", number: 11, position: "FW", club: "Wolves", age: 30 },
      { name: "Cho Gue-sung", number: 9, position: "FW", club: "Midtjylland", age: 28 },
    ],
  },
};

export const positionLabels: Record<Player["position"], string> = {
  GK: "门将",
  DF: "后卫",
  MF: "中场",
  FW: "前锋",
};

export const positionColors: Record<Player["position"], string> = {
  GK: "bg-amber-500/10 text-amber-600 dark:text-amber-400",
  DF: "bg-blue-500/10 text-blue-600 dark:text-blue-400",
  MF: "bg-emerald-500/10 text-emerald-600 dark:text-emerald-400",
  FW: "bg-rose-500/10 text-rose-600 dark:text-rose-400",
};
